# install.packages("raster")
# install.packages("rgdal")
# install.packages("sp")
# install.packages("ncdf4")
# install.packages("RNetCDF")
# install.packages("parallel")
# install.packages("magrittr")
# install.packages("data.table")
# install.packages("SPEI")
# install.packages("reservoir")
# install.packages("gtools")
# install.packages("rasterVis")
# install.packages("ggplot2")
# install.packages("ggfortify")
# install.packages("maptools")
# install.packages("rgeos")
# install.packages("PBSmapping")
# install.packages("lattice")

library(sp)
library(lattice)
library(rgdal)
library(raster)
library(ncdf4)
library(RNetCDF)
library(sp)
library(parallel)
library(magrittr)
library(data.table)
library(SPEI)
library(reservoir)
library(gtools)
library(rasterVis)
library(ggplot2)
library(zoo)
library(lubridate)
library(Metrics)
library(rgeos)
library(maptools)
library(PBSmapping)
library(dplyr)
